[package]
name = "once_unop_a_dijkstar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1"
pathfinding = "3.0.11"
serde = "1"
serde_derive = "1"
ordered-float = "2.0"
lazy_static = "1.4.0"