version: '3.9'
services:
  fprime_space:
    image: has3/quals/fprime-exploitation/challenge-space
    environment: 
      FLAG: "${FLAG}"
    networks: 
      fprime_net:
        ipv4_address: 172.16.238.2
    depends_on:
      - fprime_ground
    # ports:
    #   - "50000:50000"
  fprime_ground:
    image: has3/quals/fprime-exploitation/challenge-ground
    ports:
      # - "50050:50050"
      - "5000:5000"
      - "5001:5001"
    networks: 
      fprime_net:
        ipv4_address: 172.16.238.3
networks:
  fprime_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
  