set( CMAKE_SYSTEM_NAME Linux )
set( CMAKE_SYSTEM_VERSION 1 )


set( ARM_LOC /usr/bin)
set( ARM_PREFIX aarch64-linux-gnu-)
set( CMAKE_C_COMPILER ${ARM_LOC}/${ARM_PREFIX}gcc)
set( CMAKE_CXX_COMPILER ${ARM_LOC}/${ARM_PREFIX}g++)

set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu/ )
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

