variables:
  CHALLENGE_NAME: fly_me_to_the_moon
build:
  stage: build
  tags: 
    - has3
  script:
   - docker build -t $CHALLENGE_NAME:challenge challenge
   - docker build -t $CHALLENGE_NAME:solver solver
   - docker tag $CHALLENGE_NAME:challenge $REGISTRY_URL/$REGISTRY_PATH/$CHALLENGE_NAME:challenge
   - docker tag $CHALLENGE_NAME:solver $REGISTRY_URL/$REGISTRY_PATH/$CHALLENGE_NAME:solver

 

push:
  stage: deploy
  needs: [build]
  tags: 
    - has3
  script: 
    - docker login $REGISTRY_URL -u $REGISTRY_USER -p $REGISTRY_KEY
    - echo "Pusing to docker registry"
    - docker push $REGISTRY_URL/$REGISTRY_PATH/$CHALLENGE_NAME:challenge
    - docker push $REGISTRY_URL/$REGISTRY_PATH/$CHALLENGE_NAME:solver
    - echo "Done you fool"


